# Function and variable index
<table>
<tbody>
<tr class="odd">
<td align="left">Jump to:  </td>
<td align="left"><a href="#Function-and-variable-index_vr_symbol-1" class="summary-letter"><strong>.</strong></a>   <a href="#Function-and-variable-index_vr_symbol-2" class="summary-letter"><strong>_</strong></a>  <br />
<a href="#Function-and-variable-index_vr_letter-A" class="summary-letter"><strong>A</strong></a>   <a href="#Function-and-variable-index_vr_letter-C" class="summary-letter"><strong>C</strong></a>   <a href="#Function-and-variable-index_vr_letter-D" class="summary-letter"><strong>D</strong></a>   <a href="#Function-and-variable-index_vr_letter-E" class="summary-letter"><strong>E</strong></a>   <a href="#Function-and-variable-index_vr_letter-F" class="summary-letter"><strong>F</strong></a>   <a href="#Function-and-variable-index_vr_letter-G" class="summary-letter"><strong>G</strong></a>   <a href="#Function-and-variable-index_vr_letter-I" class="summary-letter"><strong>I</strong></a>   <a href="#Function-and-variable-index_vr_letter-L" class="summary-letter"><strong>L</strong></a>   <a href="#Function-and-variable-index_vr_letter-M" class="summary-letter"><strong>M</strong></a>   <a href="#Function-and-variable-index_vr_letter-N" class="summary-letter"><strong>N</strong></a>   <a href="#Function-and-variable-index_vr_letter-P" class="summary-letter"><strong>P</strong></a>   <a href="#Function-and-variable-index_vr_letter-R" class="summary-letter"><strong>R</strong></a>   <a href="#Function-and-variable-index_vr_letter-S" class="summary-letter"><strong>S</strong></a>   <a href="#Function-and-variable-index_vr_letter-T" class="summary-letter"><strong>T</strong></a>   <a href="#Function-and-variable-index_vr_letter-U" class="summary-letter"><strong>U</strong></a>   <a href="#Function-and-variable-index_vr_letter-V" class="summary-letter"><strong>V</strong></a>   <a href="#Function-and-variable-index_vr_letter-W" class="summary-letter"><strong>W</strong></a>  </td>
</tr>
</tbody>
</table>
<p>Index Entry</p>
<p> </p>
<p>Section</p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_symbol-1">.</a></p>
<p><a href="r-internal-structures.html#index-_002eDevice"><code class="calibre2">.Device</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Base-environment">Base environment</a></p>
<p><a href="r-internal-structures.html#index-_002eDevices"><code class="calibre2">.Devices</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Base-environment">Base environment</a></p>
<p><a href="<code-class="calibre18">.internal</code>-vs-<code-class="calibre18">.primitive</code>.html#index-_002eInternal"><code class="calibre2">.Internal</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#g_t_002eInternal-vs-_002ePrimitive">.Internal vs .Primitive</a></p>
<p><a href="r-internal-structures.html#index-_002eLast_002evalue"><code class="calibre2">.Last.value</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Base-environment">Base environment</a></p>
<p><a href="r-internal-structures.html#index-_002eOptions"><code class="calibre2">.Options</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Base-environment">Base environment</a></p>
<p><a href="<code-class="calibre18">.internal</code>-vs-<code-class="calibre18">.primitive</code>.html#index-_002ePrimitive"><code class="calibre2">.Primitive</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#g_t_002eInternal-vs-_002ePrimitive">.Internal vs .Primitive</a></p>
<p><a href="r-internal-structures.html#index-_002eRandom_002eseed"><code class="calibre2">.Random.seed</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Global-environment">Global environment</a></p>
<p><a href="r-internal-structures.html#index-_002eSavedPlots"><code class="calibre2">.SavedPlots</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Global-environment">Global environment</a></p>
<p><a href="r-internal-structures.html#index-_002eTraceback"><code class="calibre2">.Traceback</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Base-environment">Base environment</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_symbol-2">_</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fALL_005fNON_005fISO_005fC_005f"><code class="calibre2">_R_CHECK_ALL_NON_ISO_C_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fALWAYS_005fLOG_005fVIGNETTE_005fOUTPUT_005f"><code class="calibre2">_R_CHECK_ALWAYS_LOG_VIGNETTE_OUTPUT_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fASCII_005fCODE_005f"><code class="calibre2">_R_CHECK_ASCII_CODE_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fASCII_005fDATA_005f"><code class="calibre2">_R_CHECK_ASCII_DATA_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCLEAN_005fVIGN_005fTEST_005f"><code class="calibre2">_R_CHECK_CLEAN_VIGN_TEST_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCODETOOLS_005fPROFILE_005f"><code class="calibre2">_R_CHECK_CODETOOLS_PROFILE_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCODE_005fASSIGN_005fTO_005fGLOBALENV_005f"><code class="calibre2">_R_CHECK_CODE_ASSIGN_TO_GLOBALENV_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCODE_005fATTACH_005f"><code class="calibre2">_R_CHECK_CODE_ATTACH_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCODE_005fDATA_005fINTO_005fGLOBALENV_005f"><code class="calibre2">_R_CHECK_CODE_DATA_INTO_GLOBALENV_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCODE_005fUSAGE_005fVIA_005fNAMESPACES_005f"><code class="calibre2">_R_CHECK_CODE_USAGE_VIA_NAMESPACES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCODE_005fUSAGE_005fWITH_005fONLY_005fBASE_005fATTACHED_005f"><code class="calibre2">_R_CHECK_CODE_USAGE_WITH_ONLY_BASE_ATTACHED_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCODOC_005fS4_005fMETHODS_005f"><code class="calibre2">_R_CHECK_CODOC_S4_METHODS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCOMPACT_005fDATA_005f"><code class="calibre2">_R_CHECK_COMPACT_DATA_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCRAN_005fINCOMING_005f"><code class="calibre2">_R_CHECK_CRAN_INCOMING_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fCRAN_005fINCOMING_005fREMOTE_005f"><code class="calibre2">_R_CHECK_CRAN_INCOMING_REMOTE_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fDEPENDS_005fONLY_005f"><code class="calibre2">_R_CHECK_DEPENDS_ONLY_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fDEPRECATED_005fDEFUNCT_005f"><code class="calibre2">_R_CHECK_DEPRECATED_DEFUNCT_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fDOC_005fSIZES2_005f"><code class="calibre2">_R_CHECK_DOC_SIZES2_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fDOC_005fSIZES_005f"><code class="calibre2">_R_CHECK_DOC_SIZES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fDOT_005fFIRSTLIB_005f"><code class="calibre2">_R_CHECK_DOT_FIRSTLIB_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fDOT_005fINTERNAL_005f"><code class="calibre2">_R_CHECK_DOT_INTERNAL_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fEXECUTABLES_005f"><code class="calibre2">_R_CHECK_EXECUTABLES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fEXECUTABLES_005fEXCLUSIONS_005f"><code class="calibre2">_R_CHECK_EXECUTABLES_EXCLUSIONS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fEXIT_005fON_005fFIRST_005fERROR_005f"><code class="calibre2">_R_CHECK_EXIT_ON_FIRST_ERROR_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fFF_005fCALLS_005f"><code class="calibre2">_R_CHECK_FF_CALLS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fFF_005fDUP_005f"><code class="calibre2">_R_CHECK_FF_DUP_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fFORCE_005fSUGGESTS_005f"><code class="calibre2">_R_CHECK_FORCE_SUGGESTS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fGCT_005fN_005f"><code class="calibre2">_R_CHECK_GCT_N_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fINSTALL_005fDEPENDS_005f"><code class="calibre2">_R_CHECK_INSTALL_DEPENDS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fLICENSE_005f"><code class="calibre2">_R_CHECK_LICENSE_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fLIMIT_005fCORES_005f"><code class="calibre2">_R_CHECK_LIMIT_CORES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fNATIVE_005fROUTINE_005fREGISTRATION_005f"><code class="calibre2">_R_CHECK_NATIVE_ROUTINE_REGISTRATION_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fNO_005fRECOMMENDED_005f"><code class="calibre2">_R_CHECK_NO_RECOMMENDED_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fOVERWRITE_005fREGISTERED_005fS3_005fMETHODS_005f"><code class="calibre2">_R_CHECK_OVERWRITE_REGISTERED_S3_METHODS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fPERMISSIONS_005f"><code class="calibre2">_R_CHECK_PERMISSIONS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fPKG_005fSIZES_005f"><code class="calibre2">_R_CHECK_PKG_SIZES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fRD_005fCHECKRD_005fMINLEVEL_005f"><code class="calibre2">_R_CHECK_RD_CHECKRD_MINLEVEL_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fRD_005fCONTENTS_005f"><code class="calibre2">_R_CHECK_RD_CONTENTS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fRD_005fEXAMPLES_005fT_005fAND_005fF_005f"><code class="calibre2">_R_CHECK_RD_EXAMPLES_T_AND_F_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fRD_005fLINE_005fWIDTHS_005f"><code class="calibre2">_R_CHECK_RD_LINE_WIDTHS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fRD_005fSTYLE_005f"><code class="calibre2">_R_CHECK_RD_STYLE_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fRD_005fXREFS_005f"><code class="calibre2">_R_CHECK_RD_XREFS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fREPLACING_005fIMPORTS_005f"><code class="calibre2">_R_CHECK_REPLACING_IMPORTS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fS3_005fMETHODS_005fNOT_005fREGISTERED_005f"><code class="calibre2">_R_CHECK_S3_METHODS_NOT_REGISTERED_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fSCREEN_005fDEVICE_005f"><code class="calibre2">_R_CHECK_SCREEN_DEVICE_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fSKIP_005fARCH_005f"><code class="calibre2">_R_CHECK_SKIP_ARCH_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fSKIP_005fEXAMPLES_005fARCH_005f"><code class="calibre2">_R_CHECK_SKIP_EXAMPLES_ARCH_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fSKIP_005fTESTS_005fARCH_005f"><code class="calibre2">_R_CHECK_SKIP_TESTS_ARCH_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fSRC_005fMINUS_005fW_005fIMPLICIT_005f"><code class="calibre2">_R_CHECK_SRC_MINUS_W_IMPLICIT_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fSRC_005fMINUS_005fW_005fUNUSED_005f"><code class="calibre2">_R_CHECK_SRC_MINUS_W_UNUSED_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fSUBDIRS_005fNOCASE_005f"><code class="calibre2">_R_CHECK_SUBDIRS_NOCASE_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fSUBDIRS_005fSTRICT_005f"><code class="calibre2">_R_CHECK_SUBDIRS_STRICT_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fSUGGESTS_005fONLY_005f"><code class="calibre2">_R_CHECK_SUGGESTS_ONLY_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fTESTS_005fNLINES_005f"><code class="calibre2">_R_CHECK_TESTS_NLINES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fTIMINGS_005f"><code class="calibre2">_R_CHECK_TIMINGS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fTOPLEVEL_005fFILES_005f"><code class="calibre2">_R_CHECK_TOPLEVEL_FILES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fUNSAFE_005fCALLS_005f"><code class="calibre2">_R_CHECK_UNSAFE_CALLS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fUSE_005fCODETOOLS_005f"><code class="calibre2">_R_CHECK_USE_CODETOOLS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fUSE_005fINSTALL_005fLOG_005f"><code class="calibre2">_R_CHECK_USE_INSTALL_LOG_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fVC_005fDIRS_005f"><code class="calibre2">_R_CHECK_VC_DIRS_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fVIGNETTES_005fNLINES_005f"><code class="calibre2">_R_CHECK_VIGNETTES_NLINES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fWALL_005fFORTRAN_005f"><code class="calibre2">_R_CHECK_WALL_FORTRAN_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fWINDOWS_005fDEVICE_005f"><code class="calibre2">_R_CHECK_WINDOWS_DEVICE_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fXREFS_005fREPOSITORIES_005f"><code class="calibre2">_R_CHECK_XREFS_REPOSITORIES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fCHECK_005fXREFS_005fUSE_005fALIASES_005fFROM_005fCRAN_005f"><code class="calibre2">_R_CHECK_XREFS_USE_ALIASES_FROM_CRAN_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<p><a href="tools.html#index-_005fR_005fSHLIB_005fBUILD_005fOBJECTS_005fSYMBOL_005fTABLES_005f"><code class="calibre2">_R_SHLIB_BUILD_OBJECTS_SYMBOL_TABLES_</code></a>:</p>
<p> </p>
<p><a href="gui-consoles.html#Tools">Tools</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-A">A</a></p>
<p><a href="r-internal-structures.html#index-alloca"><code class="calibre2">alloca</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-ARGSUSED"><code class="calibre2">ARGSUSED</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-ATTRIB"><code class="calibre2">ATTRIB</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Attributes">Attributes</a></p>
<p><a href="r-internal-structures.html#index-attribute_005fhidden"><code class="calibre2">attribute_hidden</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Hiding-C-entry-points">Hiding C entry points</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-C">C</a></p>
<p><a href="r-internal-structures.html#index-Calloc"><code class="calibre2">Calloc</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-copyMostAttributes"><code class="calibre2">copyMostAttributes</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Attributes">Attributes</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-D">D</a></p>
<p><a href="r-internal-structures.html#index-DDVAL"><code class="calibre2">DDVAL</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-debug-bit"><code class="calibre2">debug bit</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-DispatchGeneric"><code class="calibre2">DispatchGeneric</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Argument-evaluation">Argument evaluation</a></p>
<p><a href="r-internal-structures.html#index-DispatchOrEval"><code class="calibre2">DispatchOrEval</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Argument-evaluation">Argument evaluation</a></p>
<p><a href="r-internal-structures.html#index-dump_002eframes"><code class="calibre2">dump.frames</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Global-environment">Global environment</a></p>
<p><a href="r-internal-structures.html#index-DUPLICATE_005fATTRIB"><code class="calibre2">DUPLICATE_ATTRIB</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Attributes">Attributes</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-E">E</a></p>
<p><a href="r-coding-standards.html#index-emacs"><code class="calibre2">emacs</code></a>:</p>
<p> </p>
<p><a href="tools.html#R-coding-standards">R coding standards</a></p>
<p><a href="r-internal-structures.html#index-error"><code class="calibre2">error</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Warnings-and-errors">Warnings and errors</a></p>
<p><a href="r-internal-structures.html#index-errorcall"><code class="calibre2">errorcall</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Warnings-and-errors">Warnings and errors</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-F">F</a></p>
<p><a href="r-internal-structures.html#index-Free"><code class="calibre2">Free</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-G">G</a></p>
<p><a href="r-internal-structures.html#index-gp-bits"><code class="calibre2">gp bits</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-I">I</a></p>
<p><a href="r-internal-structures.html#index-invisible"><code class="calibre2">invisible</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Autoprinting">Autoprinting</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-L">L</a></p>
<p><a href="r-internal-structures.html#index-last_002ewarning"><code class="calibre2">last.warning</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Base-environment">Base environment</a></p>
<p><a href="r-internal-structures.html#index-LEVELS"><code class="calibre2">LEVELS</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-M">M</a></p>
<p><a href="r-coding-standards.html#index-make"><code class="calibre2">make</code></a>:</p>
<p> </p>
<p><a href="tools.html#R-coding-standards">R coding standards</a></p>
<p><a href="r-coding-standards.html#index-makeinfo"><code class="calibre2">makeinfo</code></a>:</p>
<p> </p>
<p><a href="tools.html#R-coding-standards">R coding standards</a></p>
<p><a href="r-internal-structures.html#index-MISSING"><code class="calibre2">MISSING</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-MISSING-1"><code class="calibre2">MISSING</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Missingness">Missingness</a></p>
<p><a href="r-internal-structures.html#index-mkChar"><code class="calibre2">mkChar</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#The-CHARSXP-cache">The CHARSXP cache</a></p>
<p><a href="r-internal-structures.html#index-mkCharLenCE"><code class="calibre2">mkCharLenCE</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#The-CHARSXP-cache">The CHARSXP cache</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-N">N</a></p>
<p><a href="r-internal-structures.html#index-NAMED"><code class="calibre2">NAMED</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-NAMED-1"><code class="calibre2">NAMED</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Argument-evaluation">Argument evaluation</a></p>
<p><a href="<code-class="calibre18">.internal</code>-vs-<code-class="calibre18">.primitive</code>.html#index-NAMED-2"><code class="calibre2">NAMED</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#g_t_002eInternal-vs-_002ePrimitive">.Internal vs .Primitive</a></p>
<p><a href="r-internal-structures.html#index-named-bit"><code class="calibre2">named bit</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-P">P</a></p>
<p><a href="r-coding-standards.html#index-Perl"><code class="calibre2">Perl</code></a>:</p>
<p> </p>
<p><a href="tools.html#R-coding-standards">R coding standards</a></p>
<p><a href="r-internal-structures.html#index-PRIMPRINT"><code class="calibre2">PRIMPRINT</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Autoprinting">Autoprinting</a></p>
<p><a href="r-internal-structures.html#index-PRSEEN"><code class="calibre2">PRSEEN</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-R">R</a></p>
<p><a href="r-internal-structures.html#index-Rdll_002ehide"><code class="calibre2">Rdll.hide</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Hiding-C-entry-points">Hiding C entry points</a></p>
<p><a href="r-internal-structures.html#index-Realloc"><code class="calibre2">Realloc</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-R_005falloc"><code class="calibre2">R_alloc</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-R_005fAllocStringBuffer"><code class="calibre2">R_AllocStringBuffer</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-R_005fBaseNamespace"><code class="calibre2">R_BaseNamespace</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Namespaces">Namespaces</a></p>
<p><a href="r-internal-structures.html#index-R_005fCheckStack"><code class="calibre2">R_CheckStack</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-R_005fCheckStack2"><code class="calibre2">R_CheckStack2</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-R_005fFreeStringBuffer"><code class="calibre2">R_FreeStringBuffer</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-R_005fFreeStringBufferL"><code class="calibre2">R_FreeStringBufferL</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-R_005fMissingArg"><code class="calibre2">R_MissingArg</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Missingness">Missingness</a></p>
<p><a href="r-internal-structures.html#index-R_005fVisible"><code class="calibre2">R_Visible</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Autoprinting">Autoprinting</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-S">S</a></p>
<p><a href="r-internal-structures.html#index-SETLEVELS"><code class="calibre2">SETLEVELS</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-SET_005fARGUSED"><code class="calibre2">SET_ARGUSED</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-SET_005fATTRIB"><code class="calibre2">SET_ATTRIB</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Attributes">Attributes</a></p>
<p><a href="r-internal-structures.html#index-SET_005fDDVAL"><code class="calibre2">SET_DDVAL</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-SET_005fMISSING"><code class="calibre2">SET_MISSING</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-SET_005fNAMED"><code class="calibre2">SET_NAMED</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<p><a href="r-internal-structures.html#index-spare-bit"><code class="calibre2">spare bit</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-T">T</a></p>
<p><a href="r-internal-structures.html#index-trace-bit"><code class="calibre2">trace bit</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Rest-of-header">Rest of header</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-U">U</a></p>
<p><a href="r-internal-structures.html#index-UseMethod"><code class="calibre2">UseMethod</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Contexts">Contexts</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-V">V</a></p>
<p><a href="r-internal-structures.html#index-vmaxget"><code class="calibre2">vmaxget</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<p><a href="r-internal-structures.html#index-vmaxset"><code class="calibre2">vmaxset</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Memory-allocators">Memory allocators</a></p>
<hr />
<p><a href="" id="Function-and-variable-index_vr_letter-W">W</a></p>
<p><a href="r-internal-structures.html#index-warning"><code class="calibre2">warning</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Warnings-and-errors">Warnings and errors</a></p>
<p><a href="r-internal-structures.html#index-warningcall"><code class="calibre2">warningcall</code></a>:</p>
<p> </p>
<p><a href="r-internal-structures.html#Warnings-and-errors">Warnings and errors</a></p>
<hr />
<table>
<tbody>
<tr class="odd">
<td align="left">Jump to:  </td>
<td align="left"><a href="#Function-and-variable-index_vr_symbol-1" class="summary-letter"><strong>.</strong></a>   <a href="#Function-and-variable-index_vr_symbol-2" class="summary-letter"><strong>_</strong></a>  <br />
<a href="#Function-and-variable-index_vr_letter-A" class="summary-letter"><strong>A</strong></a>   <a href="#Function-and-variable-index_vr_letter-C" class="summary-letter"><strong>C</strong></a>   <a href="#Function-and-variable-index_vr_letter-D" class="summary-letter"><strong>D</strong></a>   <a href="#Function-and-variable-index_vr_letter-E" class="summary-letter"><strong>E</strong></a>   <a href="#Function-and-variable-index_vr_letter-F" class="summary-letter"><strong>F</strong></a>   <a href="#Function-and-variable-index_vr_letter-G" class="summary-letter"><strong>G</strong></a>   <a href="#Function-and-variable-index_vr_letter-I" class="summary-letter"><strong>I</strong></a>   <a href="#Function-and-variable-index_vr_letter-L" class="summary-letter"><strong>L</strong></a>   <a href="#Function-and-variable-index_vr_letter-M" class="summary-letter"><strong>M</strong></a>   <a href="#Function-and-variable-index_vr_letter-N" class="summary-letter"><strong>N</strong></a>   <a href="#Function-and-variable-index_vr_letter-P" class="summary-letter"><strong>P</strong></a>   <a href="#Function-and-variable-index_vr_letter-R" class="summary-letter"><strong>R</strong></a>   <a href="#Function-and-variable-index_vr_letter-S" class="summary-letter"><strong>S</strong></a>   <a href="#Function-and-variable-index_vr_letter-T" class="summary-letter"><strong>T</strong></a>   <a href="#Function-and-variable-index_vr_letter-U" class="summary-letter"><strong>U</strong></a>   <a href="#Function-and-variable-index_vr_letter-V" class="summary-letter"><strong>V</strong></a>   <a href="#Function-and-variable-index_vr_letter-W" class="summary-letter"><strong>W</strong></a>  </td>
</tr>
</tbody>
</table>
<hr />
<p><a href="" id="Concept-index"></a> <a href="" id="Concept-index-1"></a></p>


